spring.application.name=shortner
#spring.datasource.url=jdbc:mysql://localhost:3306/shortner
#spring.datasource.username=root
#spring.datasource.password=lovesh@12345
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
server.port=8080


# ── RDS MySQL connection ──────────────────────────
spring.datasource.url=jdbc:mysql://urlshortner-db.czg84yu8u6zd.ap-south-1.rds.amazonaws.com:3306/urlshortner\
?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=loveshkaradia
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / Hibernate ───────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Spring Boot default login credentials
spring.security.user.name=123
spring.security.user.password=123

#redis
spring.data.redis.host: localhost
spring.data.redis.port: 6379
spring.data.redis.timeout: 6000

# JWT Settings
jwt.secret=ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuvwxyz
jwt.expiration=3600000
## Rate Limiter Settings
#rate.limit.shorten.capacity=10
#rate.limit.shorten.refillMs=60000
#rate.limit.redirect.capacity=60
#rate.limit.redirect.refillMs=60000


aws.s3.bucket-name=my-url-shortener-qr-codes
aws.s3.region=ap-south-1
